In [1]:
import math
import torch
import numpy as np
from math import cos, sin, radians

c:\Anaconda3\envs\infinitt2\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [21]:
x_degree = 30
y_degree = 30
z_degree = -30
x_trans = 30
y_trans = 30
z_trans = -30

In [22]:
y_radian = radians(y_degree)
y_radian

0.5235987755982988

In [23]:
rotate_x = torch.tensor([[1, 0, 0],
                         [0, cos(radians(x_degree)), -sin(radians(x_degree))],
                         [0, sin(radians(x_degree)), cos(radians(x_degree))]])

rotate_y = torch.tensor([[cos(radians(y_degree)), 0, sin(radians(y_degree))],
                         [0, 1, 0],
                         [-sin(radians(y_degree)), 0, cos(radians(y_degree))]])

rotate_z = torch.tensor([[cos(radians(z_degree)), -sin(radians(z_degree)), 0],
                         [sin(radians(z_degree)), cos(radians(z_degree)), 0],
                         [0, 0, 1]])

In [24]:
torch.mm(rotate_x, rotate_y)

tensor([[ 0.8660,  0.0000,  0.5000],
        [ 0.2500,  0.8660, -0.4330],
        [-0.4330,  0.5000,  0.7500]])

In [25]:
torch.mm(rotate_y, rotate_x)

tensor([[ 0.8660,  0.2500,  0.4330],
        [ 0.0000,  0.8660, -0.5000],
        [-0.5000,  0.4330,  0.7500]])

In [26]:
# Rx -> Ry -> Rz -> Tx -> Ty -> Tz
tmp = torch.mm(rotate_y, rotate_x)
tmp = torch.mm(rotate_z, tmp)
matrix = torch.zeros((4,4))
for i in range(3):
    for j in range(3):
        matrix[i][j] = tmp[i][j]
matrix[0][3] = x_trans
matrix[1][3] = y_trans
matrix[2][3] = z_trans
matrix[3] = torch.tensor([0, 0, 0, 1])

In [27]:
matrix

tensor([[  0.7500,   0.6495,   0.1250,  30.0000],
        [ -0.4330,   0.6250,  -0.6495,  30.0000],
        [ -0.5000,   0.4330,   0.7500, -30.0000],
        [  0.0000,   0.0000,   0.0000,   1.0000]])